<a href="https://colab.research.google.com/github/ApplesOranges/IrisBiometricClasification/blob/main/ClasificacionDatasetCompleto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import os
import PIL
import PIL.Image
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from google.colab import drive
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
import keras
from keras.models import Sequential
from keras.layers import Dense
#from keras.utils import to_categorical 

In [4]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
files = os.listdir("/content/drive/MyDrive/IITD_database/Normalized_Images")
directory = "/content/drive/MyDrive/IITD_database/Normalized_Images"
im = PIL.Image.open(r"/content/drive/MyDrive/IITD_database/Normalized_Images/185_2.bmp")
display(im)
for f in files:
  if(int(f[:3])<225):
    im = PIL.Image.open(r"/content/drive/MyDrive/IITD_database/Normalized_Images/"+f) 
    if not os.path.exists('/content/drive/MyDrive/IITD_database/Organized_limited/'+f[:3]):
      os.makedirs('/content/drive/MyDrive/IITD_database/Organized_limited/'+f[:3]) 
    im.save('/content/drive/MyDrive/IITD_database/Organized_limited/'+f[:3]+'/'+f)

In [ ]:

x = np.zeros((1095, 48, 432))
y = []
count=-1
for i in range(1,220):
  print(i)
  for j in range(1,6):
    if(i<10):
      im = PIL.Image.open(r"/content/drive/MyDrive/IITD_database/Organized/00"+str(i)+"/"+"00"+str(i)+"_"+str(j)+".bmp")
    elif(i<100):
      im = PIL.Image.open(r"/content/drive/MyDrive/IITD_database/Organized/0"+str(i)+"/"+"0"+str(i)+"_"+str(j)+".bmp")
    else:
      im = PIL.Image.open(r"/content/drive/MyDrive/IITD_database/Organized/"+str(i)+"/"+str(i)+"_"+str(j)+".bmp")  
    im = np.asarray(im)
    t, im = cv2.threshold(im, 50, 255, cv2.THRESH_BINARY)
    count+=1
    y.append(str(i))
    for h in range(0, im.shape[0]):
      for w in range(0, im.shape[1]):
        if im[h][w] > 0:
          x[count][h][w]= 1

In [ ]:
display(pd.DataFrame(x[-1]))

In [ ]:
display(pd.DataFrame(im))

In [31]:
print(y)

['1', '1', '1', '1', '1', '2', '2', '2', '2', '2', '3', '3', '3', '3', '3', '4', '4', '4', '4', '4', '5', '5', '5', '5', '5', '6', '6', '6', '6', '6', '7', '7', '7', '7', '7', '8', '8', '8', '8', '8', '9', '9', '9', '9', '9', '10', '10', '10', '10', '10', '11', '11', '11', '11', '11', '12', '12', '12', '12', '12', '13', '13', '13', '13', '13', '14', '14', '14', '14', '14', '15', '15', '15', '15', '15', '16', '16', '16', '16', '16', '17', '17', '17', '17', '17', '18', '18', '18', '18', '18', '19', '19', '19', '19', '19', '20', '20', '20', '20', '20', '21', '21', '21', '21', '21', '22', '22', '22', '22', '22', '23', '23', '23', '23', '23', '24', '24', '24', '24', '24', '25', '25', '25', '25', '25', '26', '26', '26', '26', '26', '27', '27', '27', '27', '27', '28', '28', '28', '28', '28', '29', '29', '29', '29', '29', '30', '30', '30', '30', '30', '31', '31', '31', '31', '31', '32', '32', '32', '32', '32', '33', '33', '33', '33', '33', '34', '34', '34', '34', '34', '35', '35', '35', '35', 

In [32]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [33]:
y= y.reshape(len(y), 1)

In [34]:
display(y)

array([[  0],
       [  0],
       [  0],
       ...,
       [133],
       [133],
       [133]])

In [35]:
encoder = OneHotEncoder(sparse=False)
yhot = encoder.fit_transform(y)
display(yhot)

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,yhot,test_size=0.3)

In [37]:
x_test.shape

(329, 48, 432)

In [38]:
classifier = KNeighborsClassifier(n_neighbors=3)
nsamples, nx, ny = x_train.shape
d2_train = x_train.reshape((nsamples,nx*ny))
nsamples, nx, ny = x_test.shape
d2_test = x_test.reshape((nsamples,nx*ny))
classifier.fit(d2_train, y_train)
y_pred = classifier.predict(d2_test)
scores = metrics.accuracy_score(y_test,y_pred)

In [39]:
print(scores)

0.9027355623100304


In [40]:
display(y_test)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [41]:
display(y_pred)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [55]:
classifier = GaussianNB()
nsamples, nx, ny = x_train.shape
d2_train = x_train.reshape((nsamples,nx*ny))
nsamples, nx, ny = x_test.shape
d2_test = x_test.reshape((nsamples,nx*ny))
classifier.fit(d2_train, y_train.ravel())
y_pred = classifier.predict(d2_test)
scores = metrics.accuracy_score(y_test,y_pred)

In [56]:
print(scores)

0.6899696048632219


In [57]:
display(y_pred)

array([  7, 110,  46, 215, 135, 122, 150, 132, 184, 150, 191, 198, 175,
        75, 160, 129,  76, 208, 150,  24,  50, 187,   8,  52,  24,  60,
       195, 184, 147, 208, 191, 150, 180, 217, 181,   2, 201,  87, 208,
       150, 191, 131,  13, 208, 185,  13, 136, 194,  28,  76,  78, 159,
       184, 124,  97, 165,  36, 193,  45, 154, 150,  51,  17,  24,  35,
         6,  49, 208, 179,  74,  91, 150,  31, 198,  40, 184, 184,  96,
       183, 106, 208,  48, 117, 129, 142, 218, 164,  42, 190, 208, 124,
       149, 157,  86,  87, 148,  72, 131,  10, 146, 184, 150, 208,  71,
        83,  91,  28, 138, 119, 149, 192,  34,  97, 191, 186,  47, 196,
        16, 208, 134, 134,  50, 150,  94, 196,  83,  51, 150, 150,  56,
        50,  51,  24,  35, 195,  54,  39, 208, 112,  25,  92, 202, 185,
        24,  77, 191, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 131, 204, 194,  37, 150,  40, 114, 191, 150, 103,
        57, 151,  16,  60, 124,  39, 152, 150,  63, 150, 142, 20

In [58]:
display(y_test.flatten())

array([  7, 110,  46, 215, 135, 122,  98, 132, 205,  41,  91, 198, 175,
        75, 160, 129,  76, 204, 111, 141,  50, 187,   8,  52, 193,  60,
       195, 139, 147,  69,  52, 151, 180, 217, 181,   2, 201,  87, 204,
        27,  25, 163,  13,  69, 155,  13, 136, 194,  28,  76,  78, 159,
        80,  57,  97, 165,  36, 193,  45, 154, 201,  51,  17, 182,  35,
         6,  49,  32, 179,  74,  91, 189,  31, 198,  40,  53, 205,  96,
       183, 106,  69,  48, 117, 129, 142, 218, 164,  42, 190, 120,   1,
       163, 157,  86,  87, 148,  72, 163,  10, 146,  36,  19,  22,  71,
        83,  91,  28, 138, 119, 137, 192,  34,  97,  80, 169,  47, 196,
        16,  69, 134, 134,  50,  19,  94, 196,  83, 211, 127, 147,  56,
        50, 139,  97,  35, 195,  54,  39,  61, 112,  25,  92, 202, 155,
       182,  77, 177, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 163, 204, 194,  37,  98,  40, 114,  80, 141, 103,
        57, 151,  16,  60,   1,  39, 152,  58,  63, 123, 142, 21

In [59]:
classifier = svm.LinearSVC()
nsamples, nx, ny = x_train.shape
d2_train = x_train.reshape((nsamples,nx*ny))
nsamples, nx, ny = x_test.shape
d2_test = x_test.reshape((nsamples,nx*ny))
classifier.fit(d2_train, y_train.ravel())
y_pred = classifier.predict(d2_test)
scores = metrics.accuracy_score(y_test,y_pred)

In [60]:
print(scores)

0.9696048632218845


In [62]:
display(y_test.flatten())

array([  7, 110,  46, 215, 135, 122,  98, 132, 205,  41,  91, 198, 175,
        75, 160, 129,  76, 204, 111, 141,  50, 187,   8,  52, 193,  60,
       195, 139, 147,  69,  52, 151, 180, 217, 181,   2, 201,  87, 204,
        27,  25, 163,  13,  69, 155,  13, 136, 194,  28,  76,  78, 159,
        80,  57,  97, 165,  36, 193,  45, 154, 201,  51,  17, 182,  35,
         6,  49,  32, 179,  74,  91, 189,  31, 198,  40,  53, 205,  96,
       183, 106,  69,  48, 117, 129, 142, 218, 164,  42, 190, 120,   1,
       163, 157,  86,  87, 148,  72, 163,  10, 146,  36,  19,  22,  71,
        83,  91,  28, 138, 119, 137, 192,  34,  97,  80, 169,  47, 196,
        16,  69, 134, 134,  50,  19,  94, 196,  83, 211, 127, 147,  56,
        50, 139,  97,  35, 195,  54,  39,  61, 112,  25,  92, 202, 155,
       182,  77, 177, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 163, 204, 194,  37,  98,  40, 114,  80, 141, 103,
        57, 151,  16,  60,   1,  39, 152,  58,  63, 123, 142, 21

In [63]:
display(y_pred)

array([  7, 110,  46, 215, 135, 122,  98, 132, 171,  41,  91, 198, 175,
        75, 160, 129,  76, 204, 111, 141,  50, 187,   8,  52, 193,  60,
       195, 139, 147,  69,  52, 151, 180, 217, 181,   2, 201,  87, 204,
        27,  25, 163,  13,  69, 155,  13, 136, 194,  28,  76,  78, 159,
         4, 213,  97, 165,  36, 193,  45, 154, 201,  51,  17, 182,  35,
         6,  49,  32, 179,  74,  91, 189,  31, 198,  40,  53, 205,  96,
       183, 106,  69,  48, 117, 129, 142, 218, 164,  42, 190, 120,   1,
       163, 157,  86,  87, 148,  72, 163,  10, 146,  36,  19,  22,  71,
        83,  91,  28, 138, 119, 137, 192,  34,  97,   4, 169,  47, 196,
        16,  69, 134, 134,  50,  19,  94, 196,  83, 211, 127, 147,  56,
        50, 139,  97,  35, 195,  54,  39,  61, 112,  25,  92, 202, 155,
       182,  77, 191, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 163, 204, 194,  37,  98,  40, 114,   4, 141, 103,
        57, 151,  16,  60,   1,  39, 152,  58,  63, 123, 142, 21

In [91]:
classifier = svm.SVC(kernel="linear")#linear poly both give good scores, rbf, sigmoid perform badly
nsamples, nx, ny = x_train.shape
d2_train = x_train.reshape((nsamples,nx*ny))
nsamples, nx, ny = x_test.shape
d2_test = x_test.reshape((nsamples,nx*ny))
classifier.fit(d2_train, y_train.ravel())
y_pred = classifier.predict(d2_test)
scores = metrics.accuracy_score(y_test,y_pred)

In [92]:
print(scores)

0.9361702127659575


In [68]:
display(y_test.flatten())

array([  7, 110,  46, 215, 135, 122,  98, 132, 205,  41,  91, 198, 175,
        75, 160, 129,  76, 204, 111, 141,  50, 187,   8,  52, 193,  60,
       195, 139, 147,  69,  52, 151, 180, 217, 181,   2, 201,  87, 204,
        27,  25, 163,  13,  69, 155,  13, 136, 194,  28,  76,  78, 159,
        80,  57,  97, 165,  36, 193,  45, 154, 201,  51,  17, 182,  35,
         6,  49,  32, 179,  74,  91, 189,  31, 198,  40,  53, 205,  96,
       183, 106,  69,  48, 117, 129, 142, 218, 164,  42, 190, 120,   1,
       163, 157,  86,  87, 148,  72, 163,  10, 146,  36,  19,  22,  71,
        83,  91,  28, 138, 119, 137, 192,  34,  97,  80, 169,  47, 196,
        16,  69, 134, 134,  50,  19,  94, 196,  83, 211, 127, 147,  56,
        50, 139,  97,  35, 195,  54,  39,  61, 112,  25,  92, 202, 155,
       182,  77, 177, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 163, 204, 194,  37,  98,  40, 114,  80, 141, 103,
        57, 151,  16,  60,   1,  39, 152,  58,  63, 123, 142, 21

In [69]:
display(y_pred)

array([  7, 110,  46, 215, 135, 122,  98, 132, 184,  41,  91, 198, 175,
        75, 160, 129,  76, 204, 111, 131,  50, 187,   8,  52, 193,  60,
       195, 184, 147, 208,  52, 151, 180, 217, 181,   2, 201,  87, 204,
        27,  25, 163,  13,  69, 155,  13, 136, 194,  28,  76,  78, 159,
         4, 213,  97, 165,  36, 193,  45, 154, 201,  51,  17, 182,  35,
         6,  49,  32, 179,  74,  91, 150,  31, 198,  40,  53, 184,  96,
       183, 106,  69,  48, 117, 129, 142, 218, 164,  42, 190, 120,   1,
       163, 157,  86,  87, 148,  72, 131,  10, 146,  36,  19,  22,  71,
        83,  91,  28, 138, 119, 137, 192,  34,  97,   4, 169,  47, 196,
        16,  69, 134, 134,  50,  19,  94, 196,  83, 211, 127, 147,  56,
        50, 139,  97,  35, 195,  54,  39,  61, 112,  25,  92, 202, 155,
       182,  77, 191, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 163, 204, 194,  37, 150,  40, 114,   4, 141, 103,
        57, 151,  16,  60,   1,  39, 152,  58,  63, 123, 142, 21

In [73]:
classifier = RandomForestClassifier()
nsamples, nx, ny = x_train.shape
d2_train = x_train.reshape((nsamples,nx*ny))
nsamples, nx, ny = x_test.shape
d2_test = x_test.reshape((nsamples,nx*ny))
classifier.fit(d2_train, y_train.ravel())
y_pred = classifier.predict(d2_test)
scores = metrics.accuracy_score(y_test,y_pred)

In [74]:
print(scores)

0.8905775075987842


In [75]:
display(y_test.flatten())

array([  7, 110,  46, 215, 135, 122,  98, 132, 205,  41,  91, 198, 175,
        75, 160, 129,  76, 204, 111, 141,  50, 187,   8,  52, 193,  60,
       195, 139, 147,  69,  52, 151, 180, 217, 181,   2, 201,  87, 204,
        27,  25, 163,  13,  69, 155,  13, 136, 194,  28,  76,  78, 159,
        80,  57,  97, 165,  36, 193,  45, 154, 201,  51,  17, 182,  35,
         6,  49,  32, 179,  74,  91, 189,  31, 198,  40,  53, 205,  96,
       183, 106,  69,  48, 117, 129, 142, 218, 164,  42, 190, 120,   1,
       163, 157,  86,  87, 148,  72, 163,  10, 146,  36,  19,  22,  71,
        83,  91,  28, 138, 119, 137, 192,  34,  97,  80, 169,  47, 196,
        16,  69, 134, 134,  50,  19,  94, 196,  83, 211, 127, 147,  56,
        50, 139,  97,  35, 195,  54,  39,  61, 112,  25,  92, 202, 155,
       182,  77, 177, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 163, 204, 194,  37,  98,  40, 114,  80, 141, 103,
        57, 151,  16,  60,   1,  39, 152,  58,  63, 123, 142, 21

In [76]:
display(y_pred)

array([  7, 110,  46, 215, 135, 122,  98, 132,  13,  41,  91, 198, 175,
        75, 160, 129,  76, 204, 111, 141,  50, 187,   8,  52, 193,  60,
       195,  14, 147,  67,  52, 151, 180, 217, 181,   2, 201,  87, 204,
        27,  25, 163,  13,  69, 155,  13, 136, 194,  28,  76,  78, 159,
         6, 213,  97, 165,  36, 193,  45, 154, 201,  51,  17, 182,  35,
         6,  49,  32, 179,  74,  91,  70,  31, 198,  40, 179, 205,  96,
       183, 106,  69,  48, 117, 129, 142, 218, 164,  42, 190, 120,   1,
       163, 157,  86,  87, 148,  72, 131,  10, 146,  36,  19, 104,  71,
        83,  91,  28, 138, 119,  40, 192,  34,  97,  67, 169,  47, 196,
        16,  69, 134, 134,  50,  19,  94, 196,  83, 211, 127, 147,  56,
        50, 179,  38,  35, 195,  54,  39, 116, 112,  25,  92, 202, 155,
       182,  77, 191, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 131, 204, 194,  37,   2,  40, 114,  15, 141, 103,
        57, 151,  16,  60,  78,  39, 152,  58,  63, 123, 142, 21

In [77]:
x_train.shape

(766, 48, 432)

In [80]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(48, 432)),
  tf.keras.layers.Dense(300,activation='relu'),
  tf.keras.layers.Dense(100,activation='relu'),
  tf.keras.layers.Dense(100,activation='relu'),
  tf.keras.layers.Dense(229,activation='softmax')
])

model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

In [81]:
model.fit(x_train, y_train, epochs=30)


Epoch 1/30
24/24 [==============================] - 1s 42ms/step - loss: 6.2558 - accuracy: 0.0052
Epoch 2/30
24/24 [==============================] - 1s 41ms/step - loss: 5.3514 - accuracy: 0.0065
Epoch 3/30
24/24 [==============================] - 1s 41ms/step - loss: 5.1308 - accuracy: 0.0222
Epoch 4/30
24/24 [==============================] - 1s 41ms/step - loss: 4.5757 - accuracy: 0.0836
Epoch 5/30
24/24 [==============================] - 1s 41ms/step - loss: 3.7206 - accuracy: 0.2363
Epoch 6/30
24/24 [==============================] - 1s 41ms/step - loss: 2.4677 - accuracy: 0.4922
Epoch 7/30
24/24 [==============================] - 1s 40ms/step - loss: 1.4917 - accuracy: 0.7023
Epoch 8/30
24/24 [==============================] - 1s 41ms/step - loss: 0.6854 - accuracy: 0.8864
Epoch 9/30
24/24 [==============================] - 1s 41ms/step - loss: 0.3190 - accuracy: 0.9687
Epoch 10/30
24/24 [==============================] - 1s 40ms/step - loss: 0.1403 - accuracy: 0.9935
Epoch 11/

In [82]:
model.evaluate(x_test, y_test)

11/11 [==============================] - 0s 13ms/step - loss: 0.6476 - accuracy: 0.8784


[0.647573709487915, 0.8784194588661194]

In [83]:
pred = model.predict(x_test)
classes = np.argmax(pred, axis = 1)
print(classes)

[  7 110  46 215 135 122  98 132 191  41  91 198 175  75 160 129  76 204
 111  40  50 187   8  52 193  60 195 139 147  69   3 210 180 217 181   2
 201  87 204  49  25 163  13  69 155 191 136 194  28  76  78 159 178  79
  97 165  36 198  45 154 190  54  17 182  35   6  49  32 179  74  91 177
  31 198  40 184 205  96 183 106  69  48 117 129 142 218 164  42 190 120
   1  45 157  86  87 148  72 111  10 146  36  19 153  71  83  91  28 138
 119 172 192  34  97 178 169  47 196  16  69 134 134  50  19  94 196  83
 211 127 147  56  50  10  97  35 195  54  39  61 112  25  92 202 155 182
  77 191 110  38  23  66 156  55  68 161  84 158 183   7  90  45 204 194
  37  52  40 114 178 185 103  57 151  16  60   1  39 152  58  63 138 142
 210  38 166   7 178  85 133 184  90 188  64 155  92  58  30  19 153  18
 126 210 216  21 172 142 169 128 147 177 149 118  48 190 105 170  81  45
  20 211   5 116 157 176  66  58 214 178 145 187  96 205  88 158 200  63
  83 167 207  16  84  36 115 118  88  98  43  41  2

In [84]:
flat=y_test.flatten()
display(flat)

array([  7, 110,  46, 215, 135, 122,  98, 132, 205,  41,  91, 198, 175,
        75, 160, 129,  76, 204, 111, 141,  50, 187,   8,  52, 193,  60,
       195, 139, 147,  69,  52, 151, 180, 217, 181,   2, 201,  87, 204,
        27,  25, 163,  13,  69, 155,  13, 136, 194,  28,  76,  78, 159,
        80,  57,  97, 165,  36, 193,  45, 154, 201,  51,  17, 182,  35,
         6,  49,  32, 179,  74,  91, 189,  31, 198,  40,  53, 205,  96,
       183, 106,  69,  48, 117, 129, 142, 218, 164,  42, 190, 120,   1,
       163, 157,  86,  87, 148,  72, 163,  10, 146,  36,  19,  22,  71,
        83,  91,  28, 138, 119, 137, 192,  34,  97,  80, 169,  47, 196,
        16,  69, 134, 134,  50,  19,  94, 196,  83, 211, 127, 147,  56,
        50, 139,  97,  35, 195,  54,  39,  61, 112,  25,  92, 202, 155,
       182,  77, 177, 110,  38,  23,  66, 156,  55,  68, 161,  84, 158,
       183,   7,  90, 163, 204, 194,  37,  98,  40, 114,  80, 141, 103,
        57, 151,  16,  60,   1,  39, 152,  58,  63, 123, 142, 21